# This file was generated by GoReleaser. DO NOT EDIT.
cask "fastdeploy" do
  name "fastdeploy"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/fastdeploy"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fd"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_darwin_amd64.tar.gz"
      sha256 "5e33febceac5254713dd91ddaab934ab00a4a809cbe9a98cd98685f3bdb66c9a"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_darwin_arm64.tar.gz"
      sha256 "26108da50602ce3739ff17ccdcfdeff8a0cd8370ac668c3a2e1a018fa1aa10b0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_linux_amd64.tar.gz"
      sha256 "c2eb34b1e88b996ec746c8900fba75b28ff21a2613556f92b1d946a6ffc4e659"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_linux_arm64.tar.gz"
      sha256 "83052e08d5440e506f92a9a7bf5f19d0756f7ef5aa907ee9d907868e476d12cd"
    end
  end

  # No zap stanza required
end
