# This file was generated by GoReleaser. DO NOT EDIT.
cask "fastdeploy" do
  name "fastdeploy"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/fastdeploy"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fd"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_darwin_amd64.tar.gz"
      sha256 "8c019211bc5495e1adfb6cdadd3d709ec7d3c7422048af8ef61865336e366965"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_darwin_arm64.tar.gz"
      sha256 "4407279a9d207f1cc07007a750044b4e0ee635887a1ac18f49ebb65ea187807d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_linux_amd64.tar.gz"
      sha256 "3325c2a78bbdc18df09a220c042be64aad08812f617018148901099ff88f6005"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_linux_arm64.tar.gz"
      sha256 "e3fb817d4cb6ff6fbf2c386e4d05961dce17ad068800df36881c3333ac014e76"
    end
  end

  # No zap stanza required
end
